CREATE TABLE `users` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NOT NULL COLLATE 'utf8_spanish2_ci',
	`name` VARCHAR(100) NOT NULL COLLATE 'utf8_spanish2_ci',
	`lastname` VARCHAR(100) NOT NULL COLLATE 'utf8_spanish2_ci',
	`phone` VARCHAR(50) NOT NULL COLLATE 'utf8_spanish2_ci',
	`image` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_spanish2_ci',
	`password` VARCHAR(100) NOT NULL COLLATE 'utf8_spanish2_ci',
	`created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `phone` (`phone`) USING BTREE,
	UNIQUE INDEX `email` (`email`) USING BTREE
)
COLLATE='utf8_spanish2_ci'
ENGINE=InnoDB
AUTO_INCREMENT=24
;
